// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function CreateAbteilung(arg1:main.AbteilungProps):Promise<boolean>;

export function CreateAngebot(arg1:main.AngebotProps):Promise<boolean>;

export function CreateAnsprechpartner(arg1:main.AnsprechpartnerProps):Promise<boolean>;

export function CreateJob(arg1:main.JobProps):Promise<boolean>;

export function CreateLieferant(arg1:main.LieferantenProps):Promise<boolean>;

export function CreateMitarbeiter(arg1:main.MitarbeiterProps):Promise<boolean>;

export function CreatePartner(arg1:main.PartnerProps):Promise<boolean>;

export function DeleteAbteilung(arg1:string):Promise<boolean>;

export function DeleteAngebot(arg1:string):Promise<boolean>;

export function DeleteAnsprechpartner(arg1:string):Promise<boolean>;

export function DeleteEinkauf(arg1:string):Promise<boolean>;

export function DeleteJob(arg1:string):Promise<boolean>;

export function DeleteLieferant(arg1:string):Promise<boolean>;

export function DeleteMitabeiter(arg1:string):Promise<boolean>;

export function DeletePartner(arg1:string):Promise<boolean>;

export function GenerateWarenlieferung():Promise<boolean>;

export function GetAbteilung(arg1:string):Promise<db.Abteilung>;

export function GetAbteilungen():Promise<Array<db.Abteilung>>;

export function GetAngebot(arg1:string):Promise<db.Angebot>;

export function GetAngebote():Promise<Array<db.Angebot>>;

export function GetAnsprechpartner(arg1:string):Promise<db.Ansprechpartner>;

export function GetAnsprechpartnerFromLieferant(arg1:string):Promise<Array<db.Ansprechpartner>>;

export function GetCmsCount():Promise<db.GetCountRow>;

export function GetEinkauf(arg1:string):Promise<db.GetEinkaufRow>;

export function GetEinkaufsliste():Promise<Array<db.GetEinkaufslisteRow>>;

export function GetGeburtstagsliste():Promise<main.Geburtstagsliste>;

export function GetJob(arg1:string):Promise<db.Job>;

export function GetJobs():Promise<Array<db.Job>>;

export function GetLieferant(arg1:string):Promise<main.LieferantenResponse>;

export function GetLieferanten():Promise<Array<main.LieferantenResponse>>;

export function GetMitarbeiter():Promise<Array<db.Mitarbeiter>>;

export function GetMitarbeiterMitAbteilung():Promise<Array<db.GetMitarbeiterWithAbteilungRow>>;

export function GetOneMitarbeiter(arg1:string):Promise<db.Mitarbeiter>;

export function GetOneMitarbeiterMitAbteilung(arg1:string):Promise<db.GetOneMitarbeiterWithAbteilungRow>;

export function GetParnter(arg1:string):Promise<db.Partner>;

export function GetPartners():Promise<Array<db.Partner>>;

export function GetPdf(arg1:number):Promise<boolean>;

export function KundenFormularSuche(arg1:string):Promise<main.FormularKunde>;

export function KundenSuche(arg1:main.SearchProps):Promise<Array<main.KundenResponse>>;

export function SearchArchive(arg1:string):Promise<Array<db.SearchArchiveRow>>;

export function SendInfoMail(arg1:main.InfoProps):Promise<boolean>;

export function SendWarenlieferung():Promise<boolean>;

export function SkipEinkauf(arg1:string):Promise<boolean>;

export function SucheSeriennummer(arg1:string):Promise<any>;

export function SyncAussteller():Promise<boolean>;

export function SyncLabel():Promise<boolean>;

export function ToggleAngebot(arg1:string):Promise<boolean>;

export function UpdateAbteilung(arg1:string,arg2:main.AbteilungProps):Promise<boolean>;

export function UpdateAngebot(arg1:string,arg2:main.AngebotProps):Promise<boolean>;

export function UpdateAnsprechpartner(arg1:string,arg2:main.AnsprechpartnerProps):Promise<boolean>;

export function UpdateAussteller(arg1:main.AusstellerProps):Promise<boolean>;

export function UpdateEinkauf(arg1:main.EinkaufUpdateProps):Promise<boolean>;

export function UpdateJob(arg1:string,arg2:main.JobProps):Promise<boolean>;

export function UpdateLieferant(arg1:string,arg2:main.LieferantenProps):Promise<boolean>;

export function UpdateMitarbeiter(arg1:string,arg2:main.MitarbeiterProps):Promise<boolean>;

export function UpdatePartner(arg1:string,arg2:main.PartnerProps):Promise<boolean>;

export function UploadAusstellerImage():Promise<string>;

export function UploadImage(arg1:string,arg2:number):Promise<string>;
