// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';

export function DeleteEinkauf(arg1:string):Promise<boolean>;

export function GetEinkauf(arg1:string):Promise<db.GetEinkaufRow>;

export function GetEinkaufsliste():Promise<Array<db.GetEinkaufslisteRow>>;

export function GetGeburtstagsliste():Promise<main.Geburtstagsliste>;

export function GetMitarbeiter():Promise<Array<db.Mitarbeiter>>;

export function SkipEinkauf(arg1:string):Promise<boolean>;

export function UpdateEinkauf(arg1:main.EinkaufUpdateProps):Promise<boolean>;

export function UploadImage(arg1:string,arg2:number):Promise<string>;
