// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEinkauf(arg1) {
  return window['go']['main']['App']['DeleteEinkauf'](arg1);
}

export function GetEinkauf(arg1) {
  return window['go']['main']['App']['GetEinkauf'](arg1);
}

export function GetEinkaufsliste() {
  return window['go']['main']['App']['GetEinkaufsliste']();
}

export function GetGeburtstagsliste() {
  return window['go']['main']['App']['GetGeburtstagsliste']();
}

export function GetMitarbeiter() {
  return window['go']['main']['App']['GetMitarbeiter']();
}

export function SkipEinkauf(arg1) {
  return window['go']['main']['App']['SkipEinkauf'](arg1);
}

export function UpdateEinkauf(arg1) {
  return window['go']['main']['App']['UpdateEinkauf'](arg1);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}
