// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdmin() {
  return window['go']['main']['App']['CheckAdmin']();
}

export function CreateAbteilung(arg1) {
  return window['go']['main']['App']['CreateAbteilung'](arg1);
}

export function CreateAngebot(arg1) {
  return window['go']['main']['App']['CreateAngebot'](arg1);
}

export function CreateAnsprechpartner(arg1) {
  return window['go']['main']['App']['CreateAnsprechpartner'](arg1);
}

export function CreateJob(arg1) {
  return window['go']['main']['App']['CreateJob'](arg1);
}

export function CreateLieferant(arg1) {
  return window['go']['main']['App']['CreateLieferant'](arg1);
}

export function CreateMitarbeiter(arg1) {
  return window['go']['main']['App']['CreateMitarbeiter'](arg1);
}

export function CreatePartner(arg1) {
  return window['go']['main']['App']['CreatePartner'](arg1);
}

export function DeleteAbteilung(arg1) {
  return window['go']['main']['App']['DeleteAbteilung'](arg1);
}

export function DeleteAngebot(arg1) {
  return window['go']['main']['App']['DeleteAngebot'](arg1);
}

export function DeleteAnsprechpartner(arg1) {
  return window['go']['main']['App']['DeleteAnsprechpartner'](arg1);
}

export function DeleteEinkauf(arg1) {
  return window['go']['main']['App']['DeleteEinkauf'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteLieferant(arg1) {
  return window['go']['main']['App']['DeleteLieferant'](arg1);
}

export function DeleteMitabeiter(arg1) {
  return window['go']['main']['App']['DeleteMitabeiter'](arg1);
}

export function DeletePartner(arg1) {
  return window['go']['main']['App']['DeletePartner'](arg1);
}

export function GenerateWarenlieferung() {
  return window['go']['main']['App']['GenerateWarenlieferung']();
}

export function GetAbteilung(arg1) {
  return window['go']['main']['App']['GetAbteilung'](arg1);
}

export function GetAbteilungen() {
  return window['go']['main']['App']['GetAbteilungen']();
}

export function GetAngebot(arg1) {
  return window['go']['main']['App']['GetAngebot'](arg1);
}

export function GetAngebote() {
  return window['go']['main']['App']['GetAngebote']();
}

export function GetAnsprechpartner(arg1) {
  return window['go']['main']['App']['GetAnsprechpartner'](arg1);
}

export function GetAnsprechpartnerFromLieferant(arg1) {
  return window['go']['main']['App']['GetAnsprechpartnerFromLieferant'](arg1);
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetCmsCount() {
  return window['go']['main']['App']['GetCmsCount']();
}

export function GetEinkauf(arg1) {
  return window['go']['main']['App']['GetEinkauf'](arg1);
}

export function GetEinkaufsliste() {
  return window['go']['main']['App']['GetEinkaufsliste']();
}

export function GetGeburtstagsliste() {
  return window['go']['main']['App']['GetGeburtstagsliste']();
}

export function GetJob(arg1) {
  return window['go']['main']['App']['GetJob'](arg1);
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetLieferant(arg1) {
  return window['go']['main']['App']['GetLieferant'](arg1);
}

export function GetLieferanten() {
  return window['go']['main']['App']['GetLieferanten']();
}

export function GetMitarbeiter() {
  return window['go']['main']['App']['GetMitarbeiter']();
}

export function GetMitarbeiterMitAbteilung() {
  return window['go']['main']['App']['GetMitarbeiterMitAbteilung']();
}

export function GetOneMitarbeiter(arg1) {
  return window['go']['main']['App']['GetOneMitarbeiter'](arg1);
}

export function GetOneMitarbeiterMitAbteilung(arg1) {
  return window['go']['main']['App']['GetOneMitarbeiterMitAbteilung'](arg1);
}

export function GetParnter(arg1) {
  return window['go']['main']['App']['GetParnter'](arg1);
}

export function GetPartners() {
  return window['go']['main']['App']['GetPartners']();
}

export function GetPdf(arg1) {
  return window['go']['main']['App']['GetPdf'](arg1);
}

export function KundenFormularSuche(arg1) {
  return window['go']['main']['App']['KundenFormularSuche'](arg1);
}

export function KundenSuche(arg1) {
  return window['go']['main']['App']['KundenSuche'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SearchArchive(arg1) {
  return window['go']['main']['App']['SearchArchive'](arg1);
}

export function SendInfoMail(arg1) {
  return window['go']['main']['App']['SendInfoMail'](arg1);
}

export function SendWarenlieferung() {
  return window['go']['main']['App']['SendWarenlieferung']();
}

export function SkipEinkauf(arg1) {
  return window['go']['main']['App']['SkipEinkauf'](arg1);
}

export function SucheSeriennummer(arg1) {
  return window['go']['main']['App']['SucheSeriennummer'](arg1);
}

export function SyncAussteller() {
  return window['go']['main']['App']['SyncAussteller']();
}

export function SyncLabel() {
  return window['go']['main']['App']['SyncLabel']();
}

export function TestWarenlieferung() {
  return window['go']['main']['App']['TestWarenlieferung']();
}

export function ToggleAngebot(arg1) {
  return window['go']['main']['App']['ToggleAngebot'](arg1);
}

export function UpdateAbteilung(arg1, arg2) {
  return window['go']['main']['App']['UpdateAbteilung'](arg1, arg2);
}

export function UpdateAngebot(arg1, arg2) {
  return window['go']['main']['App']['UpdateAngebot'](arg1, arg2);
}

export function UpdateAnsprechpartner(arg1, arg2) {
  return window['go']['main']['App']['UpdateAnsprechpartner'](arg1, arg2);
}

export function UpdateAussteller(arg1) {
  return window['go']['main']['App']['UpdateAussteller'](arg1);
}

export function UpdateEinkauf(arg1) {
  return window['go']['main']['App']['UpdateEinkauf'](arg1);
}

export function UpdateJob(arg1, arg2) {
  return window['go']['main']['App']['UpdateJob'](arg1, arg2);
}

export function UpdateLieferant(arg1, arg2) {
  return window['go']['main']['App']['UpdateLieferant'](arg1, arg2);
}

export function UpdateMitarbeiter(arg1, arg2) {
  return window['go']['main']['App']['UpdateMitarbeiter'](arg1, arg2);
}

export function UpdatePartner(arg1, arg2) {
  return window['go']['main']['App']['UpdatePartner'](arg1, arg2);
}

export function UploadAusstellerImage() {
  return window['go']['main']['App']['UploadAusstellerImage']();
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}
