// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Abteilung struct {
	ID   string
	Name string
}

type Angebot struct {
	ID        string
	Title     string
	Subtitle  sql.NullString
	DateStart time.Time
	DateStop  time.Time
	Link      string
	Image     string
	Anzeigen  bool
}

type Ansprechpartner struct {
	ID          string
	Name        string
	Telefon     sql.NullString
	Mobil       sql.NullString
	Mail        sql.NullString
	Lieferantid string
}

type Aussteller struct {
	ID            int32
	Artikelnummer string
	Artikelname   string
	Specs         string
	Preis         float64
	Bild          sql.NullString
}

type Einkauf struct {
	ID          string
	Paypal      bool
	Abonniert   bool
	Geld        sql.NullString
	Pfand       sql.NullString
	Dinge       string
	Abgeschickt time.Time
	Bild1       sql.NullString
	Bild2       sql.NullString
	Bild3       sql.NullString
}

type Job struct {
	ID     string
	Name   string
	Online bool
}

type Lieferant struct {
	ID           string
	Firma        string
	Kundennummer sql.NullString
	Webseite     sql.NullString
}

type Mitarbeiter struct {
	ID              string
	Name            string
	Short           sql.NullString
	Image           bool
	Sex             sql.NullString
	Focus           sql.NullString
	Mail            sql.NullString
	Abteilungid     sql.NullString
	Einkaufid       sql.NullString
	Azubi           bool
	Geburtstag      sql.NullTime
	Gruppenwahl     sql.NullString
	Homeoffice      sql.NullString
	MobilBusiness   sql.NullString
	MobilPrivat     sql.NullString
	TelefonBusiness sql.NullString
	TelefonIntern1  sql.NullString
	TelefonIntern2  sql.NullString
	TelefonPrivat   sql.NullString
}

type Partner struct {
	ID    string
	Name  string
	Link  string
	Image string
}

type Pdf struct {
	Title string
	Body  string
	ID    int32
}

type Status struct {
	Status string
	Since  string
	ID     int32
}

type User struct {
	ID       string
	Username string
	Mail     string
	Password string
}

type Warenlieferung struct {
	Name          string
	Angelegt      time.Time
	Geliefert     sql.NullTime
	Alterpreis    sql.NullFloat64
	Neuerpreis    sql.NullFloat64
	Preis         sql.NullTime
	Artikelnummer string
	ID            int32
}
