// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEinkaufsliste() {
  return window['go']['main']['App']['GetEinkaufsliste']();
}

export function GetMitarbeiter() {
  return window['go']['main']['App']['GetMitarbeiter']();
}
