// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';

export function GetEinkaufsliste():Promise<Array<db.GetEinkaufslisteRow>>;

export function GetMitarbeiter():Promise<main.Geburtstagsliste>;
